version: '3.8'
services:
  config-server:
    image: config-server 
    restart: always
    container_name: config-server
    hostname: config-server
    ports:
      - '8888:8888'
    networks:
      - 'proyecto2'
  ms-registry-discovery-server:
    image: ms-registry-discovery-server 
    restart: always
    container_name: ms-registry-discovery-server
    hostname: ms-registry-discovery-server
    ports:
      - '8761:8761'
    depends_on:
      - 'config-server'
    networks:
      - 'proyecto2'
  ms-api-gateway:
    image: ms-api-gateway 
    restart: always
    container_name: ms-api-gateway
    ports:
      - '9191:9191'
    depends_on:
      - 'config-server'
      - 'ms-registry-discovery-server'
    networks:
      - 'proyecto2'
  ms-product:
    image: ms-product 
    restart: always
    container_name: ms-product
    ports:
      - '8001:8001'
    depends_on:
      - 'config-server'
      - 'ms-registry-discovery-server'
    networks:
      - 'proyecto2'
  ms-client:
    image: ms-client 
    restart: always
    container_name: ms-client
    ports:
      - '8002:8002'
    depends_on:
      - 'config-server'
      - 'ms-registry-discovery-server'
    networks:
      - 'proyecto2'
  ms-sales:
    image: ms-sales 
    restart: always
    container_name: ms-sales
    ports:
      - '8003:8003'
    depends_on:
      - 'config-server'
      - 'ms-registry-discovery-server'
    networks:
      - 'proyecto2'
networks:
  proyecto2: 