spring:
  cloud:
    gateway:
      routes:
        - id: ms-products
          uri: http://localhost:8001
          predicates:
            - Path=/products/**
        - id: ms-client
          uri: http://localhost:8002
          predicates:
              - Path=/clients/**
        - id: ms-sales
          uri: http://localhost:8003
          predicates:
              - Path=/sales/**
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

